package com.nativelogix.rdbms2marklogic.model.project;

import lombok.Data;

import java.util.List;

/**
 * A user-defined join between two tables that have no foreign-key relationship.
 * Supports multiple column-level conditions (AND semantics).
 */
@Data
public class SyntheticJoin {
    /** Unique identifier (generated by the frontend). */
    String id;
    String sourceSchema;
    String sourceTable;
    String targetSchema;
    String targetTable;
    List<JoinCondition> conditions;
}
